receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  logging:
    verbosity: normal
  # Future: add OTLP exporter to external backend
processors:
  batch: {}
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
